name: Daily Docker Cycle (04:40 AM IST)

on:
  schedule:
    # 23:10 UTC = 04:40 IST
    - cron: "10 23 * * *"
  workflow_dispatch:

jobs:
  docker-cycle:
    runs-on: ubuntu-latest
    timeout-minutes: 290
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Make script executable
        run: chmod +x script.sh

      - name: Run cyclic Docker script
        run: ./script.sh
